modules:
  http:
    http:
      fail_if_not_ssl: true
      fail_if_ssl: false
      method: GET
      no_follow_redirects: true
      preferred_ip_protocol: ip4
      tls_config:
        insecure_skip_verify: false
      valid_http_versions:
      - HTTP/1.1
      - HTTP/2
      valid_status_codes:
      - 200
      - 301
      - 302
      - 307
      - 308
    prober: http
    timeout: 5s
  http_websocket:
    http:
      fail_if_not_ssl: true
      fail_if_ssl: false
      method: GET
      no_follow_redirects: true
      preferred_ip_protocol: ip4
      tls_config:
        insecure_skip_verify: false
      valid_http_versions:
      - HTTP/1.1
      - HTTP/2
      - HTTP/2.0
      valid_status_codes:
      - 426
    prober: http
    timeout: 5s
  http_2xx:
    http:
      no_follow_redirects: false
      preferred_ip_protocol: ip4
      valid_http_versions:
      - HTTP/1.1
      - HTTP/2
    prober: http
    timeout: 5s
  tcp_connect_example:
    prober: tcp
    timeout: 5s
  tls_connect:
