global:
  evaluation_interval: 30s
  scrape_interval: 5s
  scrape_timeout: 5s
rule_files:
- /rules/tls.yaml
scrape_configs:
- job_name: blackbox_websocket
  metrics_path: /probe
  params:
    module:
    - http_websocket
  relabel_configs:
  - source_labels:
    - __address__
    target_label: __param_target
  - source_labels:
    - __param_target
    target_label: instance
  - replacement: blackbox:9115
    target_label: __address__
  scrape_interval: 1m
  scrape_timeout: 1m
  static_configs:
  - targets:
    - https://httpbin.org/status/426
